name: sidl_engine_context
description: Easy access to FlutterView, FlutterBinaryMessenger and FlutterTextureRegistry for FFI.
version: 0.5.6
homepage: https://github.com/SIDL-C0R0RATI0N/irondash

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sidlcorp.engine_context
        pluginClass: SidlEngineContextPlugin
      ios:
        pluginClass: SidlEngineContextPlugin
      linux:
        pluginClass: SidlEngineContextPlugin
      macos:
        pluginClass: SidlEngineContextPlugin
      windows:
        pluginClass: SidlEngineContextPluginCApi
