
[target.'aarch64-linux-android']
linker = "aarch64-linux-android-clang"
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]

[target.'armv7-linux-androideabi']
linker = "armv7a-linux-androideabi-clang"
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]

[target.'x86_64-linux-android']
linker = "x86_64-linux-android-clang"
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]

[target.'i686-linux-android']
linker = "i686-linux-android-clang"
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]
